package org.ort.gradle

/**
 * WPG/P23 (FR-AST-3, FR-AST-13, D43): renders the generated `GeneratedBundledAssetManifest.kt`
 * that `ort.android-app.gradle.kts`'s two per-flavor catalog-generation tasks emit from the root
 * `bundled-assets.json` — a plain, dependency-free Kotlin object `:app`'s `ModelCatalog`
 * (`ModelsViewData.kt`) maps into its own `ModelCatalogEntry` shape.
 *
 * Extracted from the precompiled script plugin (where it originally lived as a set of top-level
 * functions) into a plain object here so it is directly unit-testable — a Gradle script's own
 * top-level functions are not reachable from `buildSrc/src/test/kotlin`; a plain object in
 * `buildSrc/src/main/kotlin` is (the same split [FetchBundledAssetsTask]/[BundledAssetFetcher]
 * already established for that task's own logic).
 *
 * One call renders exactly one flavor's catalog. [bundled] is `true` for the `full` variant
 * (FR-AST-3 — every asset ships inside the installed artifact, so [downloadUrl] is never needed)
 * and `false` for `play` (FR-AST-13 — nothing is bundled, so every entry carries its
 * [BundledAssetManifest.Entry.mirrorUrl] as [downloadUrl] instead). Both flavors' output still
 * carries every build-time bundling field (`url`/`sha256`/`sizeBytes`/`destination`/`tiers`/
 * `licence`/`gated`) unchanged from before this field pair existed — this only adds what a
 * downloading variant needs, never removes what every variant already had.
 */
object BundledAssetCatalogRenderer {

    private const val MAX_LINE_LENGTH = 120

    fun render(entries: List<BundledAssetManifest.Entry>, bundled: Boolean): String = buildString {
        val flavor = if (bundled) "Full" else "Play"
        appendLine("package org.ort.app.assets")
        appendLine()
        appendLine("// GENERATED by :app's generate${flavor}BundledAssetCatalog task (buildSrc/")
        appendLine("// ort.android-app.gradle.kts) from the repo root's bundled-assets.json (WPG, FR-AST-3,")
        appendLine("// FR-AST-13). Do not edit by hand — edit that file and rebuild.")
        appendLine()
        appendLine("public data class GeneratedBundledAssetEntry(")
        appendLine("    public val id: String,")
        appendLine("    public val url: String,")
        appendLine("    public val sha256: String,")
        appendLine("    public val sizeBytes: Long,")
        appendLine("    public val destination: String,")
        appendLine("    public val tiers: List<String>,")
        appendLine("    public val licence: String,")
        appendLine("    public val gated: Boolean,")
        appendLine("    /** FR-AST-13/D43: true on the \"full\" variant — every asset ships inside the")
        appendLine("     * installed artifact (FR-AST-3). False on \"play\", where this entry is not")
        appendLine("     * bundled and must be downloaded from [downloadUrl] during setup (FR-AST-10..12). */")
        appendLine("    public val bundled: Boolean,")
        appendLine("    /** FR-AST-14/D44: the models-v1 mirror URL to download this entry from when")
        appendLine("     * [bundled] is false. Blank when [bundled] is true — the \"full\" variant never")
        appendLine("     * downloads anything (AC-190). */")
        appendLine("    public val downloadUrl: String,")
        appendLine(")")
        appendLine()
        appendLine("public object GeneratedBundledAssetManifest {")
        appendLine("    public val entries: List<GeneratedBundledAssetEntry> = listOf(")
        entries.forEach { e ->
            appendLine("        GeneratedBundledAssetEntry(")
            appendLine("            id = ${kotlinString(e.id)},")
            appendLine(kotlinFieldLine(indent = "            ", name = "url", value = e.url))
            appendLine("            sha256 = ${kotlinString(e.sha256)},")
            appendLine("            sizeBytes = ${e.sizeBytes}L,")
            appendLine("            destination = ${kotlinString(e.destination)},")
            appendLine("            tiers = listOf(${e.tiers.joinToString(", ") { kotlinString(it) }}),")
            appendLine("            licence = ${kotlinString(e.licence)},")
            appendLine("            gated = ${e.gated},")
            appendLine("            bundled = $bundled,")
            appendLine(
                kotlinFieldLine(
                    indent = "            ",
                    name = "downloadUrl",
                    value = if (bundled) "" else e.mirrorUrl,
                ),
            )
            appendLine("        ),")
        }
        appendLine("    )")
        appendLine("}")
    }

    fun kotlinString(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""

    /**
     * Renders a `$name = "value",` field line, splitting [value] across a `+`-concatenated pair of
     * string literals when the single-line form would exceed ktlint's 120-column limit (several of
     * the real manifest's URLs do) — generated code is still checked by ktlint like any other
     * source file, so this keeps the output itself compliant rather than special-casing generated
     * files out of the gate.
     */
    fun kotlinFieldLine(indent: String, name: String, value: String): String {
        val singleLine = "$indent$name = ${kotlinString(value)},"
        if (singleLine.length <= MAX_LINE_LENGTH) return singleLine
        val midpoint = value.length / 2
        val splitAt = value.lastIndexOf('/', midpoint).let { if (it in 1 until value.length - 1) it + 1 else midpoint }
        val first = value.substring(0, splitAt)
        val second = value.substring(splitAt)
        return "$indent$name = ${kotlinString(first)} +\n$indent    ${kotlinString(second)},"
    }
}
