import com.android.build.gradle.internal.dsl.BaseAppModuleExtension
import org.gradle.api.tasks.testing.Test
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.ort.gradle.BundledAssetManifest
import org.ort.gradle.FetchBundledAssetsTask
import org.ort.gradle.FetchSherpaNativeTask
import org.ort.gradle.NativeLibraryPackagingGuardTask
import org.ort.gradle.SherpaNativeManifest
import java.io.File

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    // P13 (D15 — Compose): the Compose compiler is its own Gradle plugin from Kotlin 2.0 on,
    // resolved from buildSrc's own classpath (buildSrc/build.gradle.kts), pinned there to the
    // exact Kotlin version applied above so compiler and language version can never drift apart.
    id("org.jetbrains.kotlin.plugin.compose")
    id("ort.common")
}

// P13: the version catalog (`libs`) defined in the root build's settings.gradle.kts is not
// visible inside a buildSrc precompiled script plugin — buildSrc is a separate build with its
// own classpath (see buildSrc/build.gradle.kts). Coordinates below are therefore hardcoded,
// deliberately kept in exact sync with the `composeBom`/`activityCompose` entries in
// gradle/libs.versions.toml, which is what app/build.gradle.kts (a normal project script, where
// `libs` *is* visible) uses for its own compose-adjacent test dependencies.
val composeBomCoordinate = "androidx.compose:compose-bom:2024.09.03"
val activityComposeCoordinate = "androidx.activity:activity-compose:1.9.3"

extensions.configure<BaseAppModuleExtension> {
    namespace = "org.ort.app"
    compileSdk = 34

    defaultConfig {
        applicationId = "org.ort.app"
        minSdk = 26
        targetSdk = 34
        versionCode = 2
        versionName = "0.1.1"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // R-1001 (register): exactly the two ABIs this project fetches native libraries for
        // (sherpa-native.json, FetchSherpaNativeTask) — arm64-v8a is the operator's phone, x86_64
        // is the audit AVDs (so the tour can exercise real ASR for the first time). Deliberately
        // NOT armeabi-v7a/x86: the APK is already ~600 MB with every bundled model, and this
        // project ships no 32-bit-only device in its device matrix (spec/test-plan.md).
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // P13 (D15): Compose lands here so every Android module built on this convention plugin has
    // it available — today that is only `:app`, the reader UI's home.
    buildFeatures {
        compose = true
    }

    // P13: Compose's own UI-testing rule (`createComposeRule`, used by the new tests under
    // ui/) launches its host activity via the debug-only stub `ui-test-manifest` provides
    // (declared debugImplementation below, per upstream guidance — it must never ship in
    // release). `test`/`check`/`build` otherwise also run the *same* test source set against the
    // release variant's merged manifest, which never carries that stub, and those tests fail
    // there for a reason that has nothing to do with the code under test. One unit-test build
    // type, run against the manifest that actually carries what these tests need.
    testBuildType = "debug"
}

extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension> {
    jvmToolchain(17)
}

/**
 * Renders [entries] as the generated `GeneratedBundledAssetManifest.kt` — a plain, dependency-free
 * Kotlin object [org.ort.app.ui.data.ModelCatalog] maps into its own [org.ort.app.ui.data.ModelCatalogEntry]
 * shape (WPG). A Kotlin string literal, never a raw copy of the JSON: [BundledAssetManifest.Entry]'s
 * fields are typed (`Long`, `List<String>`, `Boolean`), so a malformed manifest fails here, at
 * generation time, rather than as a runtime parse error inside the shipped app.
 */
fun renderCatalogKotlin(entries: List<BundledAssetManifest.Entry>): String = buildString {
    appendLine("package org.ort.app.assets")
    appendLine()
    appendLine("// GENERATED by :app's generateBundledAssetCatalog task (buildSrc/ort.android-app.gradle.kts)")
    appendLine("// from the repo root's bundled-assets.json (WPG, FR-AST-3). Do not edit by hand — edit that")
    appendLine("// file and rebuild.")
    appendLine()
    appendLine("public data class GeneratedBundledAssetEntry(")
    appendLine("    public val id: String,")
    appendLine("    public val url: String,")
    appendLine("    public val sha256: String,")
    appendLine("    public val sizeBytes: Long,")
    appendLine("    public val destination: String,")
    appendLine("    public val tiers: List<String>,")
    appendLine("    public val licence: String,")
    appendLine("    public val gated: Boolean,")
    appendLine(")")
    appendLine()
    appendLine("public object GeneratedBundledAssetManifest {")
    appendLine("    public val entries: List<GeneratedBundledAssetEntry> = listOf(")
    entries.forEach { e ->
        appendLine("        GeneratedBundledAssetEntry(")
        appendLine("            id = ${kotlinString(e.id)},")
        appendLine(kotlinFieldLine(indent = "            ", name = "url", value = e.url))
        appendLine("            sha256 = ${kotlinString(e.sha256)},")
        appendLine("            sizeBytes = ${e.sizeBytes}L,")
        appendLine("            destination = ${kotlinString(e.destination)},")
        appendLine("            tiers = listOf(${e.tiers.joinToString(", ") { kotlinString(it) }}),")
        appendLine("            licence = ${kotlinString(e.licence)},")
        appendLine("            gated = ${e.gated},")
        appendLine("        ),")
    }
    appendLine("    )")
    appendLine("}")
}

fun kotlinString(value: String): String =
    "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""

/**
 * Renders a `$name = "value",` field line, splitting [value] across a `+`-concatenated pair of
 * string literals when the single-line form would exceed ktlint's 120-column limit (the encoder/
 * decoder/Gemma URLs all do) — generated code is still checked by `ktlintMainSourceSetCheck` like
 * any other source file (deliberately not excluded: a generator producing lint-failing code is a
 * real defect in the generator, not something to hide from the linter), so this keeps the output
 * itself compliant rather than special-casing generated files out of the gate.
 */
fun kotlinFieldLine(indent: String, name: String, value: String): String {
    val singleLine = "$indent$name = ${kotlinString(value)},"
    if (singleLine.length <= MAX_GENERATED_LINE_LENGTH) return singleLine
    val midpoint = value.length / 2
    val splitAt = value.lastIndexOf('/', midpoint).let { if (it in 1 until value.length - 1) it + 1 else midpoint }
    val first = value.substring(0, splitAt)
    val second = value.substring(splitAt)
    return "$indent$name = ${kotlinString(first)} +\n$indent    ${kotlinString(second)},"
}

val MAX_GENERATED_LINE_LENGTH = 120

// WPG (spec/e2e-capture-modes-plan.md, FR-AST-3/3a/3b, D35/D36): bundled assets — build-time
// fetch, catalogue generation, first-launch verify. Two tasks, deliberately independent of each
// other:
//
//  - `generateBundledAssetCatalog` reads the committed `bundled-assets.json` (root) and emits a
//    plain Kotlin source file — `ModelCatalog` (app/.../ui/data/ModelsViewData.kt) is built from
//    its output, so the app and the build agree by construction (no second, hand-typed catalogue
//    to drift). This needs no network and no HF_TOKEN: it only reads the manifest's own committed
//    text, so `:app:testDebugUnitTest` and ordinary compilation work offline. A generated Kotlin
//    object was chosen over a runtime resource read (e.g. an asset `ModelCatalog` parses via
//    `Context.getAssets()`) because every existing call site (`ModelCatalog.entries`, `.entry(id)`,
//    `.specFor(id, filesDir)`) is a plain, Context-free API a dozen files outside this package's
//    ownership already call — switching to a runtime read would need a `Context` at every one of
//    them. A generated object keeps that surface identical.
//  - `fetchBundledAssets` ([FetchBundledAssetsTask]) does the real network fetch, verification and
//    packaging into `src/main/assets/bundled/` (gitignored) — the thing that actually needs
//    HF_TOKEN and needs to run exactly once per verified asset, cached at
//    `$GRADLE_USER_HOME/ort-bundled-assets/` across worktrees.
//
// `assembleDebug`/`assembleRelease` (and therefore `build`) depend on `fetchBundledAssets` so a
// shipping artifact is never produced without every bundled asset verified (FR-AST-3: one build
// variant, no first-run download). They do NOT depend on `generateBundledAssetCatalog` explicitly
// — every Kotlin compile task does, below, which assemble already depends on transitively.
val bundledAssetManifestFile = rootProject.layout.projectDirectory.file("bundled-assets.json")
val generatedBundledAssetCatalogDir = layout.buildDirectory.dir("generated/ort/bundledAssetCatalog/kotlin")

val generateBundledAssetCatalog = tasks.register("generateBundledAssetCatalog") {
    group = "build"
    description = "Generates GeneratedBundledAssetManifest.kt from the root bundled-assets.json (WPG, FR-AST-3)."
    inputs.file(bundledAssetManifestFile)
    outputs.dir(generatedBundledAssetCatalogDir)
    doLast {
        val entries = BundledAssetManifest.parse(bundledAssetManifestFile.asFile.readText())
        val packageDir = generatedBundledAssetCatalogDir.get().asFile.resolve("org/ort/app/assets")
        packageDir.mkdirs()
        File(packageDir, "GeneratedBundledAssetManifest.kt").writeText(renderCatalogKotlin(entries))
    }
}

extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension> {
    sourceSets.getByName("main").kotlin.srcDir(generatedBundledAssetCatalogDir)
}

tasks.withType<KotlinCompile>().configureEach { dependsOn(generateBundledAssetCatalog) }

// ktlint/detekt scan the main source set's directories directly (not through a KotlinCompile task),
// so they hit the identical implicit-input validation problem the merge*Assets wiring above
// explains — generateBundledAssetCatalog needs no network and costs nothing, so a hard `dependsOn`
// (not `mustRunAfter`) is the right call here, unlike fetchBundledAssets.
tasks.matching { it.name.contains("Ktlint", ignoreCase = true) || it.name.contains("detekt", ignoreCase = true) }
    .configureEach { dependsOn(generateBundledAssetCatalog) }

val fetchBundledAssets = tasks.register<FetchBundledAssetsTask>("fetchBundledAssets") {
    group = "build"
    description = "Fetches, verifies and packages every bundled asset into src/main/assets/bundled (WPG, FR-AST-3)."
    manifestFile.set(bundledAssetManifestFile)
    assetsOutputDir.set(layout.projectDirectory.dir("src/main/assets/bundled"))
    cacheRoot.set(layout.dir(providers.provider { gradle.gradleUserHomeDir.resolve("ort-bundled-assets") }))
    hfToken.set(providers.environmentVariable("HF_TOKEN"))
    // The one local-development escape hatch (never set by CI — see .github/workflows and
    // FetchBundledAssetsTask's own KDoc): -PortAllowMissingBundledAssets=true or
    // ORT_ALLOW_MISSING_BUNDLED_ASSETS=1.
    allowMissingBundledAssets.set(
        providers.gradleProperty("ortAllowMissingBundledAssets").map { it.toBoolean() }
            .orElse(providers.environmentVariable("ORT_ALLOW_MISSING_BUNDLED_ASSETS").map { it == "1" })
            .orElse(false),
    )
}

tasks.matching { it.name == "assembleDebug" || it.name == "assembleRelease" }.configureEach {
    dependsOn(fetchBundledAssets)
}

// CI regression (register, 2026-09-11, commit 8a8e8ea1): a fresh checkout has no
// `app/src/main/assets/bundled/` (gitignored) and `:app:testDebugUnitTest` never pulled
// `fetchBundledAssets` into its own task graph — the assembleDebug/assembleRelease `dependsOn`
// above only helps when one of *those* is also requested, and the broad `mustRunAfter` sweep
// below deliberately excludes `UnitTest`-named tasks, so a plain `:app:testDebugUnitTest`
// invocation (exactly what CI's `android` job and Robolectric run) never scheduled the fetch at
// all. Robolectric reads assets through `mergeDebugUnitTestAssets`, which itself depends on
// `mergeDebugAssets` (AGP's own wiring, not ours) to combine the main and test asset sets — so a
// direct `dependsOn(fetchBundledAssets)` on `mergeDebugAssets`/`mergeReleaseAssets` (the two
// *main*-variant merge tasks, matched by exact name so no other task's assets are touched) is
// the one place that reaches both the real app and every test that reads its packaged assets
// through one real dependency edge, not a same-invocation-only ordering hint. This does mean
// `:app:testDebugUnitTest` now needs a real `HF_TOKEN` (or the escape hatch) to run standalone,
// same as `assembleDebug` always has — deliberate, per this fix: tests and the app must see the
// identical packaged asset set (FR-AST-3), never a fresher one than what shipped. `HF_TOKEN`
// absent behaves exactly as before: `fetchBundledAssets` fails with its one-line message unless
// `-PortAllowMissingBundledAssets=true`/`ORT_ALLOW_MISSING_BUNDLED_ASSETS=1` is set, in which case
// it packages the 4 non-gated assets and marks the gated one `missing`.
tasks.matching { it.name == "mergeDebugAssets" || it.name == "mergeReleaseAssets" }.configureEach {
    dependsOn(fetchBundledAssets)
}

// R-1001 (register): sherpa-onnx's Android native libraries — see FetchSherpaNativeTask's own KDoc
// for the full defect account and sherpa-native.json for the manifest. Deliberately NOT wired to
// -PortAllowMissingBundledAssets/ORT_ALLOW_MISSING_BUNDLED_ASSETS the way fetchBundledAssets is
// (lead correction, WPJ build report): the archive needs no token and costs tens, not hundreds, of
// megabytes — a build that silently shipped without these libraries is the exact defect (R-1001)
// this task exists to close, so there is no escape hatch and a fetch failure always fails the
// build, in every environment including a plain no-token local iteration.
val sherpaNativeManifestFile = rootProject.layout.projectDirectory.file("sherpa-native.json")

val fetchSherpaNativeLibraries = tasks.register<FetchSherpaNativeTask>("fetchSherpaNativeLibraries") {
    group = "build"
    description = "Fetches, verifies and packages sherpa-onnx's Android native libraries into " +
        "src/main/jniLibs (register R-1001)."
    manifestFile.set(sherpaNativeManifestFile)
    jniLibsOutputDir.set(layout.projectDirectory.dir("src/main/jniLibs"))
    cacheRoot.set(layout.dir(providers.provider { gradle.gradleUserHomeDir.resolve("ort-sherpa-native") }))
}

tasks.matching { it.name == "assembleDebug" || it.name == "assembleRelease" }.configureEach {
    dependsOn(fetchSherpaNativeLibraries)
}

// Same implicit-input shape fetchBundledAssets' own comment documents for mergeDebugAssets/
// mergeReleaseAssets, for the AGP task family that actually reads src/main/jniLibs directly.
tasks.matching { it.name == "mergeDebugJniLibFolders" || it.name == "mergeReleaseJniLibFolders" }.configureEach {
    dependsOn(fetchSherpaNativeLibraries)
}

// R-1001: the structural guard (audit F-027's own family, PlatformGuards.kt) that closes the gap
// every declared-artifact check in that file cannot — see NativeLibraryPackagingGuardTask's own
// KDoc for why it reads the real APK instead. Wired here, not the root platformGuards task, because
// this needs an assembled APK to exist first and dependencyRules/platformGuards/build's own
// ordering (root build.gradle.kts, outside this package's ownership) runs platformGuards before
// any variant is assembled. `:app:check`/`:app:build` already reach it, and the root `build` task
// depends on every subproject's own `check` (root build.gradle.kts), so a plain `./gradlew build`
// still exercises this guard on every push.
val verifySherpaNativeLibrariesPackaged = tasks.register<NativeLibraryPackagingGuardTask>(
    "verifySherpaNativeLibrariesPackaged",
) {
    group = "verification"
    description = "Fails if the packaged debug APK is missing a required sherpa-onnx native " +
        "library for any required ABI (register R-1001)."
    apkFile.set(layout.buildDirectory.file("outputs/apk/debug/app-debug.apk"))
    dependsOn("assembleDebug")
}

tasks.named("check") { dependsOn(verifySherpaNativeLibrariesPackaged) }

// `app/src/main/assets/bundled/` (fetchBundledAssets' own output) is an *implicit* input to a
// whole family of AGP-internal tasks that read the main variant's assets directly — not just
// `mergeDebugAssets`/`mergeReleaseAssets`, but also lint's own model-writer tasks
// (`generateDebugLintReportModel` and siblings), found by actually running the full `build` task
// and reading what Gradle's own task-validation named next, rather than guessed up front. Running
// any of them in the same build as `fetchBundledAssets` with no declared relationship trips
// Gradle's validation ("uses this output ... without declaring an explicit or implicit
// dependency"). Enumerating every such AGP task by name is whack-a-mole — a new AGP version can
// add another one — so this orders **every** task in this project after `fetchBundledAssets`
// except the two kinds that must never be coupled to it:
//
//  - `fetchBundledAssets`/`generateBundledAssetCatalog` themselves (ordering a task after itself
//    is a Gradle error).
//  - Anything with `UnitTest`/`AndroidTest` in its name — `mustRunAfter` on these would be
//    redundant, not a relaxation: since the fix above made `mergeDebugAssets`/`mergeReleaseAssets`
//    (and therefore `mergeDebugUnitTestAssets`/`mergeDebugAndroidTestAssets`, which AGP wires to
//    depend on the corresponding main-variant merge) carry a real `dependsOn(fetchBundledAssets)`,
//    every unit/instrumentation test that reads the merged assets already has a `dependsOn`-strength
//    ordering guarantee — a stronger property than `mustRunAfter` gives, so adding the weaker hint
//    on top would say nothing new. `:app:testDebugUnitTest` therefore DOES need a real `HF_TOKEN`
//    (or the escape hatch) to run standalone now, same as `assembleDebug` — see the
//    `mergeDebugAssets`/`mergeReleaseAssets` block above for why.
//
// `mustRunAfter`, deliberately not `dependsOn`, for every one of them: it only orders the two
// tasks *when both are already scheduled* — true for `assembleDebug`/`assembleRelease` (which
// `dependsOn` the fetch task explicitly, above), for `mergeDebugAssets`/`mergeReleaseAssets` (ditto,
// above) and every task that in turn depends on any of those (which now includes the test tasks).
tasks.matching { task ->
    task.name != fetchBundledAssets.name &&
        task.name != generateBundledAssetCatalog.name &&
        !task.name.contains("UnitTest") &&
        !task.name.contains("AndroidTest")
}.configureEach {
    mustRunAfter(fetchBundledAssets)
}

// CI regression (register, 2026-09-11, release run 34664670909): Robolectric's own
// `Asset$_CompressedAsset.getBuffer` inflates a compressed APK asset entirely into the test JVM's
// heap the moment a test reads it — and now that `mergeDebugAssets` (above) guarantees the real,
// 555 MB `LLM_GEMMA3_1B` asset is actually present for `:app:testDebugUnitTest` to read, any test
// that copies it through the real `AndroidBundledAssetSource` (not the fixture source) forces that
// entire inflation, which the JVM test worker's default heap cannot hold — `OutOfMemoryError: Java
// heap space` killed the release workflow's unit-test job. Raising `org.gradle.jvmargs` (the
// *daemon's* heap, R-807c) does not help here: `Test` tasks fork their own worker JVM with its own,
// separate heap, sized by `maxHeapSize`, not the daemon's. Set explicitly rather than left at
// Gradle's default (512m), which is what OOM'd.
//
// The alternative deliberately not taken: `androidResources.noCompress` for `.task`/`.onnx` would
// let Robolectric (and the real Android runtime) map the asset file instead of inflating it, since
// an uncompressed APK entry can be read directly rather than decompressed into memory — but AAPT2
// already compresses these binary, already-dense model formats poorly, so marking them
// non-compressed would grow the shipped APK from the measured ~611 MB (results/e2e-audit/
// installed-size.md, R18) to an estimated ~724 MB — a real, permanent cost to every install for a
// test-JVM-only problem. Documented here as an option, not applied.
tasks.withType<Test>().configureEach {
    maxHeapSize = "3g"
}

// P13: `testBuildType` above only redirects the `test`/`check` task *aliases* — `build`'s own
// dependency graph still wires up `testReleaseUnitTest` regardless, and that variant's merged
// manifest never carries `ui-test-manifest` (debug-only, correctly — see the dependency comment
// below), so it fails on every Compose UI test for a reason that has nothing to do with the code
// under test. The release build type differs from debug only by `isMinifyEnabled`, so testing it
// separately proves nothing `testDebugUnitTest` does not already prove; disable it outright.
tasks.matching { it.name == "testReleaseUnitTest" }.configureEach { enabled = false }

dependencies {
    "implementation"(platform(composeBomCoordinate))
    "implementation"("androidx.compose.ui:ui")
    "implementation"("androidx.compose.ui:ui-graphics")
    "implementation"("androidx.compose.ui:ui-tooling-preview")
    "implementation"("androidx.compose.material3:material3")
    "implementation"("androidx.compose.foundation:foundation")
    "implementation"(activityComposeCoordinate)
    "debugImplementation"("androidx.compose.ui:ui-tooling")
    // The debug-only stub activity ui-test-junit4/createComposeRule launches when a test does not
    // provide its own — declared debugImplementation (not testImplementation) because it must be
    // merged into the manifest the "test" build variant compiles against, same as upstream Compose
    // testing setup guides document.
    "debugImplementation"("androidx.compose.ui:ui-test-manifest")

    "testImplementation"(platform(composeBomCoordinate))
    "testImplementation"("androidx.compose.ui:ui-test-junit4")

    "androidTestImplementation"(platform(composeBomCoordinate))
    "androidTestImplementation"("androidx.compose.ui:ui-test-junit4")
    "androidTestImplementation"("androidx.test.ext:junit:1.2.1")
    "androidTestImplementation"("androidx.test:runner:1.6.2")
    "androidTestImplementation"("androidx.test:core:1.6.1")
}
